[versions]
kotlin = "1.7.20"
kotlinx-serialization-json = "1.4.1"
kotlinx-serialization-converter = "0.8.0"
compose = "1.3.3"
corektx = "1.9.0"
appcompat = "1.5.1"
activity = "1.6.1"
lifecycle = "2.5.1"
navigation = "2.5.3"
startup = "1.1.1"
security = "1.0.0"
compose-compiler = "1.3.2"

material = "1.7.0"
accompanist = "0.28.0"
in-app-update = "2.0.1"
secret-gradle-plugin = "2.0.1"

junit = "4.13.2"
androidx-test-junit = "1.1.5"
androidx-test-espresso = "3.5.1"

gradleplugin = "7.3.1"
kspplugin = "1.7.20-1.0.8"

dagger-hilt = "2.44.2"
dagger-hilt-navigation-compose = "1.0.0"
flipper = "0.176.1"
soloader = "0.10.5"
okhttp = "4.10.0"
retrofit = "2.9.0"
timber = "5.0.1"
compose-destination = "1.7.22-beta"

google-services = "4.3.14"
crashlytics = "2.9.2"
firebase = "31.1.1"
ktlint = "11.0.0"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "gradleplugin" }
kotlin-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "corektx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
security = { module = "androidx.security:security-crypto", version.ref = "security" }

material = { module = "com.google.android.material:material", version.ref = "material" }
inappupdate = { module = "com.google.android.play:app-update-ktx", version.ref = "in-app-update" }
secret-plugin = { group = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", name = "secrets-gradle-plugin", version.ref = "secret-gradle-plugin" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-destination-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destination" }
compose-destination-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destination" }
compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "dagger-hilt-navigation-compose" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-noop = { module = "com.facebook.flipper:flipper-noop", version.ref = "flipper" }
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }
flipper-network = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
hilt-kapt = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
hilt-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "dagger-hilt" }

google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
crashlytics-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
firebase = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }

ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }

[bundles]
compose = [
    "compose-ui",
    "compose-foundation",
    "compose-ui-tooling",
    "compose-activity",
    "compose-animation",
    "compose-viewmodel",
    "compose-material",
    "compose-material-icons-extended",
    "compose-material-icons",
    "compose-runtime",
    "compose-ui-tooling-preview",
    "compose-hilt-navigation"
]
compose-test = ["compose-junit"]
compose-android-test = ["compose-ui-test"]
android-test = ["androidx-test-junit", "androidx-test-espresso"]
okhttp = ["okhttp", "okhttp-logging-interceptor"]
flipper = ["flipper", "soloader"]
firebase = ["firebase-analytics", "firebase-crashlytics"]
accompanist = ["accompanist-systemuicontroller"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspplugin" }
secret = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secret-gradle-plugin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
