[versions]
balloonCompose = "1.6.12"
compileSdk = "35"
minSdk = "30"
targetSdk = "35"
appVersion = "3.0.10"
versionCode = "30010"

kotlin = "2.2.0"
kotlinx-serialization-json = "1.9.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1-0.6.x-compat"
kotlinx-collections-immutable = "0.4.0"
javax-inject = "1"
corektx = "1.16.0"
appcompat = "1.7.1"
activity = "1.10.1"
fragmentKtx = "1.8.8"
lifecycle = "2.9.1"
swipe-refresh-layout = "1.1.0"
navigation = "2.9.1"
startup = "1.2.0"
customtab = "1.8.0"
exifinterface = "1.4.1"
compose-bom = "2025.06.01"
androidx-paging = "3.3.6"
desugarJdk = "2.1.5"

material = "1.12.0"
in-app-update = "2.1.0"
secret-gradle-plugin = "2.0.1"

junit = "4.13.2"
androidx-test-junit = "1.2.1"
androidx-test-espresso = "3.6.1"
junit5-plugin = "1.13.1.0"
junit5-jupiter = "5.13.3"
truth = "1.4.4"
robolectric = "4.15.1"
androidx-uiautomator = "2.3.0"
androidx-test = "1.6.2"
androidx-test-rules = "1.6.1"
mockk = "1.14.4"

gradleplugin = "8.11.1"
kspplugin = "2.2.0-2.0.2"

dagger-hilt = "2.56.2"
dagger-hilt-navigation-compose = "1.2.0"
flipper = "0.273.0"
soloader = "0.12.1"
okhttp = "4.12.0"
retrofit = "3.0.0"
timber = "5.0.1"
compose-destination = "1.11.9"
coil = "2.7.0"
coil3 = "3.2.0"
lottie = "6.6.7"
dotsindicator = "5.1.0"
deepLinkDispatch = "6.2.2"
rin = "0.3.0"
mozilla-component-utils = "140.0.4"

google-services = "4.4.3"
crashlytics = "3.0.4"
firebase = "33.16.0"
firebaseMessagingLifecycleKtx = "0.3.0"
app-distribution = "5.1.1"
ktlint = "12.3.0"
process-pheonix = "3.0.0"
amplitude = "1.21.4"
spotless = "7.2.1"
constraintlayout = "2.2.1"
benchmark-macro-junit4 = "1.3.4"
androidx-baselineprofile = "1.3.4"
profileinstaller = "1.4.1"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "gradleplugin" }
balloon-compose = { module = "com.github.skydoves:balloon-compose", version.ref = "balloonCompose" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlin-coroutines-google-play = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javax-inject" }

activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "corektx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
swipe-refresh-layout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipe-refresh-layout" }
startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
desugarLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdk" }
customtab = { module = "androidx.browser:browser", version.ref = "customtab" }

material = { module = "com.google.android.material:material", version.ref = "material" }
inappupdate = { module = "com.google.android.play:app-update-ktx", version.ref = "in-app-update" }
secret-plugin = { group = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", name = "secrets-gradle-plugin", version.ref = "secret-gradle-plugin" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-three = { module = "androidx.compose.material3:material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-junit = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-destination-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destination" }
compose-destination-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destination" }
compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "dagger-hilt-navigation-compose" }
compose-lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
compose-paging = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
# For accesss of ComposeCompilerGradlePluginExtension
compose-compiler-extension = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil3-test = { group = "io.coil-kt.coil3", name = "coil-test", version.ref = "coil3" }
coil3-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3" }
coil3-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil3" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
junit5 = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5-jupiter" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5-jupiter" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5-jupiter" }
junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5-jupiter" }
junit5-android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version = "1.8.0" }
junit5-android-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version = "1.8.0" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-uiautomator" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }

flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-noop = { module = "com.facebook.flipper:flipper-noop", version.ref = "flipper" }
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }
flipper-network = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

retrofit-bom = { module = "com.squareup.retrofit2:retrofit-bom", version.ref = "retrofit" }
retrofit = { module = "com.squareup.retrofit2:retrofit" }
retrofit-kotlin-serialization-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization" }
retrofit-response-type-keeper = { module = "com.squareup.retrofit2:response-type-keeper" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
hilt-ksp = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
hilt-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "dagger-hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger-hilt" }
hilt-testing-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt" }

google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
crashlytics-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
firebase = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-messaging-lifecycle-ktx = { module = "com.github.skydoves:firebase-messaging-lifecycle-ktx", version.ref = "firebaseMessagingLifecycleKtx" }

ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }

process-phoenix = { module = "com.jakewharton:process-phoenix", version.ref = "process-pheonix" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
amplitude-android = { module = "com.amplitude:analytics-android", version.ref = "amplitude" }
android-lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
deeplink-dispatch = { group = "com.airbnb", name = "deeplinkdispatch", version.ref = "deepLinkDispatch" }
deeplink-dispatch-processor = { group = "com.airbnb", name = "deeplinkdispatch-processor", version.ref = "deepLinkDispatch" }
rin = { module = "io.github.takahirom.rin:rin", version.ref = "rin" }
mozilla-component-utils = { module = "org.mozilla.components:support-utils", version.ref = "mozilla-component-utils" }

[bundles]
compose = [
    "compose-ui",
    "compose-foundation",
    "compose-ui-tooling",
    "compose-activity",
    "compose-animation",
    "compose-viewmodel",
    "compose-material",
    "compose-material-three",
    "compose-material-icons-extended",
    "compose-material-icons",
    "compose-runtime",
    "compose-ui-tooling-preview",
    "compose-hilt-navigation",
    "compose-lottie",
]
compose-test = ["compose-junit"]
compose-android-test = ["compose-ui-test"]
android-test = ["androidx-test-junit", "androidx-test-espresso"]
okhttp = ["okhttp", "okhttp-logging-interceptor"]
flipper = ["flipper", "soloader"]
firebase = ["firebase-analytics", "firebase-crashlytics", "firebase-messaging"]
junit5-test = ["junit5", "junit5-engine", "junit5-params", "junit5-vintage"]
androidx-android-test = ["androidx-test-runner", "androidx-test-rules", "androidx-uiautomator"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspplugin" }
secret = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secret-gradle-plugin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "junit5-plugin" }
app-distribution = { id = "com.google.firebase.appdistribution", version.ref = "app-distribution" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidTest = { id = "com.android.test", version.ref = "gradleplugin" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-baselineprofile" }
